name: alfred_emoji_workflow
description: Search for emojis and copy them to the clipboard easily.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  algolia: ^1.1.1
  args: ^2.3.1
  alfred_workflow: ^0.2.11
  cli_script: ^0.2.6
  crypto: ^3.0.2
  emojis: ^0.9.9
  envied: ^0.3.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  path: ^1.8.3
  stash: ^4.4.1

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.2.1
  envied_generator: ^0.3.0
  json_serializable: ^6.5.4
  lints: ^2.0.1
